# Generated by Django 5.0.1 on 2024-01-27 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name="Bike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=200)),
                ("model_code", models.CharField(max_length=100)),
                ("engine", models.CharField(max_length=100, null=True)),
                ("chassi", models.CharField(max_length=100, unique=True)),
                ("registration_plate", models.CharField(max_length=20, null=True)),
                ("color", models.CharField(max_length=50, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("new", "New"), ("pre_owned", "Pre-owned")],
                        default="new",
                        max_length=10,
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=9, null=True
                    ),
                ),
                (
                    "wholesale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=9, null=True
                    ),
                ),
                (
                    "wholesale_price_net",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=9, null=True
                    ),
                ),
                ("received_date", models.DateField(null=True)),
                ("sold", models.BooleanField(default=False)),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("Honda", "Honda"),
                            ("Yamaha", "Yamaha"),
                            ("GPX", "GPX"),
                        ],
                        default="Honda",
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("id_card_number", models.CharField(max_length=13)),
                ("age", models.IntegerField()),
                ("dob", models.DateField(null=True)),
                ("address", models.CharField(max_length=200)),
                ("district", models.CharField(max_length=200, null=True)),
                ("subdistrict", models.CharField(max_length=200, null=True)),
                ("province", models.CharField(max_length=200, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("ML", "Male"), ("FL", "Female"), ("OT", "Other")],
                        max_length=2,
                    ),
                ),
                ("phone", models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("storage_name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sale_date", models.DateField()),
                ("total_price", models.FloatField(default=0)),
                ("discount", models.IntegerField(default=0)),
                ("down_payment", models.FloatField(default=0, null=True)),
                ("commission", models.FloatField(blank=True, default=0, null=True)),
                ("total", models.FloatField(default=0, null=True)),
                ("payment_method", models.CharField(max_length=50)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "registration_status",
                    models.CharField(
                        choices=[("CPL", "Complete"), ("IPL", "Incomplete")],
                        max_length=3,
                    ),
                ),
                ("has_checkout", models.BooleanField(default=False)),
                (
                    "additional_fees",
                    models.ManyToManyField(blank=True, to="api.additionalfee"),
                ),
                ("bikes", models.ManyToManyField(to="api.bike")),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.customer",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bike",
            name="storage_place",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.storage",
            ),
        ),
        migrations.CreateModel(
            name="StorageTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transfer_date", models.DateField(auto_now_add=True)),
                ("bikes", models.ManyToManyField(to="api.bike")),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="destination_transfer",
                        to="api.storage",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="origin_transfer",
                        to="api.storage",
                    ),
                ),
            ],
        ),
    ]
