# Generated by Django 4.2 on 2024-02-14 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storagetransfer",
            name="destination",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="destination_transfer",
                to="api.storage",
            ),
        ),
        migrations.AlterField(
            model_name="storagetransfer",
            name="origin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="origin_transfer",
                to="api.storage",
            ),
        ),
    ]
