# Generated by Django 5.0.2 on 2024-07-29 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='quantity',
            new_name='stock',
        ),
        migrations.CreateModel(
            name='OrderGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gift')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='gifts',
            field=models.ManyToManyField(blank=True, to='api.ordergift'),
        ),
    ]
