# Generated by Django 4.2 on 2024-02-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_storagetransfer_destination_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bike",
            name="invoice_number",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bike",
            name="invoice_picture",
            field=models.ImageField(blank=True, null=True, upload_to="invoices/%Y/%m/"),
        ),
    ]
