# Generated by Django 5.0.2 on 2024-09-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_quantity_gift_stock_ordergift_order_gifts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='gifts',
            field=models.ManyToManyField(blank=True, null=True, to='api.ordergift'),
        ),
    ]
